# Configuration for https://pre-commit.ci
autofix_prs: true
autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit hooks"
autoupdate_branch: ""
autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
autoupdate_schedule: weekly
skip: []
submodules: false
