name: Debricked scan

on: [pull_request]

jobs:
  vulnerabilities-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
