[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "out"

[[redirects]]
  from = "/api/*"
  to = "https://financial-asset-relationship-db-git-fe-9a2856-mohavros-projects.vercel.app/api/:splat"
  status = 200
  force = true
