app::FinancialAssetApp
Optional[AssetRelationshipGraph] app.FinancialAssetApp::graph
Referenced by app.FinancialAssetApp._initialize_graph, app.FinancialAssetApp.create_interface, app.FinancialAssetApp.ensure_graph.
app.FinancialAssetApp::refresh_all_outputs
app.FinancialAssetApp::refresh_visualization
app.FinancialAssetApp::generate_formulaic_analysis
app.FinancialAssetApp::show_formula_details
app.FinancialAssetApp::update_asset_info
app.FinancialAssetApp.__init__(self)
AssetRelationshipGraph app.FinancialAssetApp.ensure_graph(self)
Ensures the graph is initialized, re-creating sample data if it's None.
References app.FinancialAssetApp._initialize_graph, app.FinancialAssetApp.graph.
Referenced by app.FinancialAssetApp.generate_formulaic_analysis, app.FinancialAssetApp.refresh_all_outputs, app.FinancialAssetApp.refresh_visualization.
app.FinancialAssetApp.update_all_metrics_outputs(self, AssetRelationshipGraph graph)
Updates all metric-related visualizations and text.
References app.FinancialAssetApp._update_metrics_text.
Referenced by app.FinancialAssetApp.refresh_all_outputs.
app.FinancialAssetApp.refresh_all_outputs(self, AssetRelationshipGraph graph_state)
Refreshes all visualizations and reports in the Gradio interface.
References app.FinancialAssetApp.ensure_graph, app.FinancialAssetApp.update_all_metrics_outputs.
app.FinancialAssetApp.refresh_visualization(self, graph_state, view_mode, layout_type, show_same_sector, show_market_cap, show_correlation, show_corporate_bond, show_commodity_currency, show_income_comparison, show_regulatory, show_all_relationships, toggle_arrows)
Refresh visualization with 2D/3D mode support and relationship filtering.
References app.FinancialAssetApp.ensure_graph.
app.FinancialAssetApp.generate_formulaic_analysis(self, AssetRelationshipGraph graph_state)
Generate comprehensive formulaic analysis of the asset graph.
References app.FinancialAssetApp._format_formula_summary, app.FinancialAssetApp.ensure_graph.
app.FinancialAssetApp.show_formula_details(self, str formula_name, AssetRelationshipGraph graph_state)
Show detailed view of a specific formula.
app.FinancialAssetApp.create_interface(self)
Creates the Gradio interface for the Financial Asset Relationship Database.
References app.FinancialAssetApp.graph.
None app.FinancialAssetApp._initialize_graph(self)
Initializes the asset graph, creating a sample database if necessary.
References app.FinancialAssetApp.graph.
Referenced by app.FinancialAssetApp.ensure_graph.
str app.FinancialAssetApp._update_metrics_text(AssetRelationshipGraph graph)
Generates the formatted text for network statistics.
Referenced by app.FinancialAssetApp.update_all_metrics_outputs.
str app.FinancialAssetApp._format_formula_summary(Dict summary, Dict analysis_results)
Format the formula analysis summary for display.
Referenced by app.FinancialAssetApp.generate_formulaic_analysis.
Tuple[Dict, Dict] app.FinancialAssetApp.update_asset_info(Optional[str] selected_asset, AssetRelationshipGraph graph)
Retrieves and formats detailed information for a selected asset.