tests::unit::test_graph_2d_visuals
tests.unit.test_graph_2d_visuals.create_relationship_traces_with_defaults(graph, positions, asset_ids, **overrides)
Helper to call _create_2d_relationship_traces with default parameters.
Referenced by tests.unit.test_graph_2d_visuals.TestRelationshipTraces.test_create_2d_relationship_traces_empty_graph, tests.unit.test_graph_2d_visuals.TestRelationshipTraces.test_create_2d_relationship_traces_selective_filtering, tests.unit.test_graph_2d_visuals.TestRelationshipTraces.test_create_2d_relationship_traces_show_all, tests.unit.test_graph_2d_visuals.TestRelationshipTraces.test_create_2d_relationship_traces_with_relationships.