api::auth
api::auth.SECRET_KEY
str api::auth.ALGORITHM
int api::auth.ACCESS_TOKEN_EXPIRE_MINUTES
api::auth.pwd_context
api::auth.oauth2_scheme
api::auth.user_repository
bool api.auth._is_truthy(str|None value)
Determine whether a string value represents a truthy boolean. Parameters: value (str | None): Input string to evaluate; recognised truthy forms are "true", "1", "yes" and "on" (case-insensitive). Returns: bool: True if `value` matches a recognised truthy form, False otherwise.
Referenced by api.auth._seed_credentials_from_env.
api.auth.verify_password(plain_password, hashed_password)
Verify whether a plaintext password matches a stored hashed password. Returns: `True` if the plaintext password matches the hashed password, `False` otherwise.
Referenced by api.auth.authenticate_user.
api.auth.get_password_hash(password)
Hash a plaintext password using the configured password-hashing context. Parameters: password (str): Plaintext password to hash. Returns: str: The hashed password.
Referenced by api.auth._seed_credentials_from_env.
None api.auth._seed_credentials_from_env(UserRepository repository)
Seed an administrative user into the repository from environment variables. If both ADMIN_USERNAME and ADMIN_PASSWORD are set, create or update that user in the repository using optional ADMIN_EMAIL, ADMIN_FULL_NAME and ADMIN_DISABLED (interpreted as a truthy flag). The provided password is stored hashed. If either ADMIN_USERNAME or ADMIN_PASSWORD is missing, no changes are made.
References api.auth._is_truthy, api.auth._seed_credentials_from_env, api.auth.get_password_hash.
Referenced by api.auth._seed_credentials_from_env.
Optional[UserInDB] api.auth.get_user(str username, Optional[UserRepository] repository=None)
Retrieve a user by username. Parameters: repository (Optional[UserRepository]): Repository to query; if omitted the module-level `user_repository` is used. Returns: Optional[UserInDB]: The matching UserInDB instance, or `None` if no user exists with that username.
Referenced by api.auth.authenticate_user, api.auth.get_current_user.
UserInDB | bool api.auth.authenticate_user(str username, str password, Optional[UserRepository] repository=None)
Authenticate a username and password and return the corresponding stored user. Parameters: username (str): Username to authenticate. password (str): Plaintext password to verify. repository (Optional[UserRepository]): Repository to query for the user; if omitted the module-level repository is used. Returns: UserInDB when authentication succeeds, `False` otherwise.
References api.auth.get_user, api.auth.verify_password.
api.auth.create_access_token(dict data, Optional[timedelta] expires_delta=None)
Create a JWT access token that includes an expiry (`exp`) claim. Parameters: data (dict): Claims to include in the token payload. The function will add or overwrite the `exp` claim. expires_delta (Optional[timedelta]): Time span after which the token expires; if omitted the token expires in 15 minutes. Returns: str: Encoded JWT as a compact string.
api.auth.get_current_user(str token=Depends(oauth2_scheme))
Return the user represented by the provided JWT. Returns: User: The User model corresponding to the token's subject. Raises: HTTPException: 401 with detail "Token has expired" if the token has expired. HTTPException: 401 with detail "Could not validate credentials" if the token is invalid, missing the subject, or no matching user is found.
References api.auth.get_user.
api.auth.get_current_active_user(User current_user=Depends(get_current_user))
Get the currently authenticated active user. Raises: HTTPException: 400 with detail "Inactive user" if the user's account is disabled. Returns: The authenticated user's public profile as a `User` instance.