tests::integration::test_workflow_requirements_integration
str tests::integration::test_workflow_requirements_integration.WORKFLOWS_DIR
str tests::integration::test_workflow_requirements_integration.REQUIREMENTS_FILE
List[Tuple[str, str]] tests.integration.test_workflow_requirements_integration.parse_requirements(Path file_path)
Parse a pip-style requirements file into a list of package names with their version specifiers. Ignores blank lines and lines beginning with '#'. Extras and environment markers on a requirement line are ignored for matching. Parameters: file_path (Path): Path to a requirements file (e.g., requirements-dev.txt). Returns: List[Tuple[str, str]]: List of (package_name, version_specifier) tuples; `version_specifier` is the specifier string or an empty string if none. Raises: ValueError: If any non-empty, non-comment line cannot be parsed as a requirement.
Referenced by tests.integration.test_workflow_requirements_integration.TestRequirementsMatchWorkflowNeeds.test_has_pytest_for_testing, tests.integration.test_workflow_requirements_integration.TestRequirementsMatchWorkflowNeeds.test_has_required_dev_tools, tests.integration.test_workflow_requirements_integration.TestPyYAMLAvailability.test_pyyaml_in_requirements_for_workflow_validation, tests.integration.test_workflow_requirements_integration.TestPyYAMLAvailability.test_types_pyyaml_provides_type_hints.