tests::integration::test_requirements_dev
str tests::integration::test_requirements_dev.REQUIREMENTS_FILE
List[Tuple[str, str]] tests.integration.test_requirements_dev.parsed_requirements()
Parse requirements file and return list of (package, version_spec) tuples.
References tests.integration.test_requirements_dev.parse_requirements.
str tests.integration.test_requirements_dev._extract_package_name(str line, Requirement req)
Extract the package name from a requirement line, preserving original casing. Args: line: The raw requirement line from the file. req: The parsed Requirement object. Returns: The package name as written in the requirements file.
Referenced by tests.integration.test_requirements_dev._parse_single_requirement.
str tests.integration.test_requirements_dev._normalize_specifier(str specifier_str)
Normalize a version specifier string by removing spaces around commas. Args: specifier_str: The version specifier string to normalize. Returns: The normalized specifier string.
Referenced by tests.integration.test_requirements_dev._parse_single_requirement.
tuple tests.integration.test_requirements_dev._parse_single_requirement(str line)
Parse a single requirement line into (package, version_spec) tuple. Args: line: A stripped, non-empty, non-comment line from the requirements file. Returns: A tuple of (package_name, version_specifier) or None if parsing fails.
References tests.integration.test_requirements_dev._extract_package_name, tests.integration.test_requirements_dev._normalize_specifier.
List[Tuple[str, str]] tests.integration.test_requirements_dev.parse_requirements(Path file_path)
Parse requirements file and return list of (package, version_spec) tuples. Examples: Input line: "requests>=2.25.0" Output: ("requests", ">=2.25.0") Input line: "pytest>=6.0,<7.0 # testing framework" Output: ("pytest", ">=6.0,<7.0") Input line: "pandas" Output: ("pandas", "") Input line: "package[extra1,extra2]>=1.0" Output: ("package", ">=1.0") Raises: ValueError: If a requirement line is malformed. OSError: If the requirements file could not be opened or read. ...
Referenced by tests.integration.test_requirements_dev.TestPackageConsistency.package_names, tests.integration.test_requirements_dev.parsed_requirements, tests.integration.test_requirements_dev.TestSpecificChanges.requirements, tests.integration.test_requirements_dev.TestEdgeCasesAndErrorHandling.test_empty_lines_and_comments_ignored, tests.integration.test_requirements_dev.TestFileOrganization.test_has_appropriate_number_of_packages, tests.integration.test_requirements_dev.TestEdgeCasesAndErrorHandling.test_parse_inline_comments, tests.integration.test_requirements_dev.TestEdgeCasesAndErrorHandling.test_parse_packages_with_environment_markers, tests.integration.test_requirements_dev.TestEdgeCasesAndErrorHandling.test_parse_packages_with_extras, tests.integration.test_requirements_dev.TestEdgeCasesAndErrorHandling.test_whitespace_handling, tests.integration.test_requirements_dev.TestPyYAMLIntegration.test_yaml_parsing_capability.