tests::integration::test_requirements
str tests::integration::test_requirements.REQUIREMENTS_FILE
List[Tuple[str, str]] tests.integration.test_requirements.parse_requirements(Path file_path)
Parse requirements file and return list of (package, version_spec) tuples. Examples: Input line: "requests>=2.25.0" Output: ("requests", ">=2.25.0") Input line: "pytest>=6.0,<7.0 # testing framework" Output: ("pytest", ">=6.0,<7.0") Input line: "pandas" Output: ("pandas", "") Input line: "package[extra1,extra2]>=1.0" Output: ("package", ">=1.0") Raises: ValueError: If a requirement line is malformed. OSError: If the requirements file could not be opened or read.
Referenced by tests.integration.test_requirements.TestComprehensiveValidation.requirements, tests.integration.test_requirements.TestPackageConsistency.requirements, tests.integration.test_requirements.TestRequiredPackages.requirements, tests.integration.test_requirements.TestSecurityAndCompliance.requirements, tests.integration.test_requirements.TestVersionSpecifications.requirements, tests.integration.test_requirements.TestEdgeCases.test_empty_lines_ignored, tests.integration.test_requirements.TestEdgeCases.test_parse_with_environment_markers, tests.integration.test_requirements.TestEdgeCases.test_parse_with_extras, tests.integration.test_requirements.TestEdgeCases.test_parse_with_inline_comments.