graph_visuals
graph_visuals.logger
graph_visuals._graph_access_lock
graph_visuals.REL_TYPE_COLORS
bool graph_visuals._is_valid_color_format(str color)
Validate if a string is a valid color format. Supports common color formats: - Hex colors (#RGB, #RRGGBB, #RRGGBBAA) - RGB/RGBA (e.g., 'rgb(255,0,0)', 'rgba(255,0,0,0.5)') - Named colors (delegated to Plotly) Args: color: Color string to validate Returns: True if color format is valid, False otherwise
Referenced by _get_line_style, _validate_colors_list.
Dict[str, int] graph_visuals._build_asset_id_index(List[str] asset_ids)
Build O(1) lookup index for asset IDs to their positions.
Referenced by _create_directional_arrows, _create_relationship_traces.
Dict[Tuple[str, str, str], float] graph_visuals._build_relationship_index(AssetRelationshipGraph graph, Iterable[str] asset_ids)
Build optimized relationship index for O(1) lookups with pre-filtering and thread safety. This function consolidates relationship data into a single index structure that can be efficiently queried for: - Checking if a relationship exists (O(1) lookup) - Getting relationship strength (O(1) lookup) - Detecting bidirectional relationships (O(1) reverse lookup) Performance optimizations: - Pre-filters graph.relationships to only include relevant source_ids - Uses set-based membership tests for O(1) lookups - Avoids unnecessary iterations over irrelevant relationships - Reduces continue statements by filtering upfront Thread Safety: ============== This function uses a reentrant lock (RLock) to protect concurrent access to graph.relationships within this module. However, true thread safety requires coordination across the entire codebase. Implementation: - Uses threading.RLock (_graph_access_lock) to synchronize access to graph.relationships - The lock is reentrant, allowing the same thread to acquire it multiple times safely - Creates a snapshot of relationships within the lock to minimize lock hold time Thread safety guarantees (with conditions): ✓ SAFE: Multiple threads calling visualization functions in this module concurrently ✓ SAFE: Concurrent calls to this function with the same graph object ⚠ CONDITIONAL: Concurrent modifications to graph.relationships are only safe if: - All code that modifies graph.relationships uses the same _graph_access_lock, OR - The graph object is treated as immutable after creation (recommended approach) Recommended usage patterns for thread safety: 1. PREFERRED: Treat graph objects as immutable after creation. Build the graph completely before passing it to visualization functions. This eliminates the need for locking. 2. ALTERNATIVE: If you must modify graph.relationships concurrently, ensure all modification code acquires _graph_access_lock before accessing graph.relationships. This requires coordination across your entire codebase. Note: The AssetRelationshipGraph class itself does not implement any locking mechanisms. Thread safety for modifications must be managed by the calling code. If other parts of your application modify graph.relationships without using _graph_access_lock, race conditions may occur. Error Handling (addresses review feedback): =========================================== This function implements comprehensive error handling to ensure robustness: - Validates that graph is an AssetRelationshipGraph instance - Validates that graph.relationships exists and is a properly formatted dictionary - Validates that asset_ids is iterable and contains only strings - Validates each relationship tuple has the correct structure (3 elements) - Validates data types for target_id (string), rel_type (string), and strength (numeric) - Provides detailed error messages indicating the exact location and nature of any issues Args: graph: The asset relationship graph asset_ids: Iterable of asset IDs to include (will be converted to a set for O(1) membership tests) Returns: Dictionary mapping (source_id, target_id, rel_type) to strength for all relationships Raises: TypeError: If graph is not an AssetRelationshipGraph instance, or if data types are invalid ValueError: If graph.relationships has invalid structure or malformed data
Referenced by _collect_and_group_relationships, _create_directional_arrows.
go.Scatter3d graph_visuals._create_node_trace(np.ndarray positions, List[str] asset_ids, List[str] colors, List[str] hover_texts)
Create node trace for 3D visualization with comprehensive input validation. Validates all inputs to ensure: - positions is a non-empty 2D numpy array with shape(n, 3) containing finite numeric values - asset_ids is a non-empty list or tuple of non-empty strings with length matching positions - colors is a non-empty list or tuple of valid color strings with length matching positions - hover_texts is a non-empty list or tuple of strings with length matching positions Args: positions: NumPy array of node positions with shape(n, 3) containing finite numeric values asset_ids: List of asset ID strings (must be non-empty strings, length must match positions) colors: List of node colors(length must match positions) hover_texts: List of hover texts(length must match positions) Returns: Plotly Scatter3d trace for nodes Raises: ValueError: If input parameters are invalid, have mismatched dimensions, or contain invalid data
References _validate_visualization_data.
Referenced by _validate_visualization_data, visualize_3d_graph_with_filters.
str graph_visuals._generate_dynamic_title(int num_assets, int num_relationships, str base_title="Financial Asset Network")
Generate a dynamic title for the visualization based on asset and relationship counts. This function creates a consistent title format across different visualization contexts, improving modularity and making it easier to customize titles without modifying core logic. Args: num_assets: Number of assets in the visualization num_relationships: Number of relationships displayed base_title: Base title text(default: "Financial Asset Network") Returns: Formatted title string with asset and relationship counts
Referenced by _prepare_layout_config, _validate_visualization_data.
int graph_visuals._calculate_visible_relationships(List[go.Scatter3d] relationship_traces)
Calculate the number of visible relationships from traces. This helper function extracts the relationship count calculation logic, making it reusable and testable independently of the visualization logic. Args: relationship_traces: List of Scatter3d traces representing relationships Returns: Number of visible relationships(edges) in the traces
Referenced by _prepare_layout_config.
Tuple[str, Dict[str, object]] graph_visuals._prepare_layout_config(int num_assets, List[go.Scatter3d] relationship_traces, str base_title="Financial Asset Network", Optional[Dict[str, object]] layout_options=None)
Prepare layout configuration with dynamic title based on visualization data. This function separates layout configuration logic from the main visualization function, improving modularity and making it easier to customize layouts in different contexts. Args: num_assets: Number of assets in the visualization relationship_traces: List of relationship traces to count visible relationships base_title: Base title text (default: "Financial Asset Network") layout_options: Optional layout customization options Returns: Tuple of (dynamic_title, layout_options) ready for use with _configure_3d_layout
References _calculate_visible_relationships, _generate_dynamic_title.
Referenced by visualize_3d_graph_with_filters.
None graph_visuals._add_directional_arrows_to_figure(go.Figure fig, AssetRelationshipGraph graph, np.ndarray positions, List[str] asset_ids)
Add directional arrows to the figure for unidirectional relationships using batch operations.
References _create_directional_arrows.
None graph_visuals._configure_3d_layout(go.Figure fig, str title, Optional[Dict[str, object]] options=None)
Configure the 3D layout for the figure. Args: fig: Target Plotly figure title: Title text options: Optional mapping to override defaults. Supported keys: - width(int) - height(int) - gridcolor(str) - bgcolor(str) - legend_bgcolor(str) - legend_bordercolor(str)
Referenced by visualize_3d_graph_with_filters.
None graph_visuals._validate_positions_array(np.ndarray positions)
Validate positions array structure and values.
Referenced by _validate_visualization_data.
None graph_visuals._validate_asset_ids_list(List[str] asset_ids)
Validate asset_ids list structure and content.
Referenced by _validate_visualization_data.
None graph_visuals._validate_colors_list(List[str] colors, int expected_length)
Validate colors list structure, content, and format.
References _is_valid_color_format.
Referenced by _validate_visualization_data.
None graph_visuals._validate_hover_texts_list(List[str] hover_texts, int expected_length)
Validate hover_texts list structure and content.
Referenced by _validate_visualization_data.
None graph_visuals._validate_asset_ids_uniqueness(List[str] asset_ids)
Validate that asset IDs are unique.
Referenced by _validate_visualization_data.
None graph_visuals._validate_visualization_data(np.ndarray positions, List[str] asset_ids, List[str] colors, List[str] hover_texts)
Validate visualization data integrity to prevent runtime errors.
References _create_directional_arrows, _create_node_trace, _create_relationship_traces, _generate_dynamic_title, _validate_asset_ids_list, _validate_asset_ids_uniqueness, _validate_colors_list, _validate_hover_texts_list, _validate_positions_array, _validate_visualization_data.
Referenced by _create_node_trace, _validate_visualization_data, visualize_3d_graph_with_filters.
Dict[Tuple[str, bool], List[dict]] graph_visuals._collect_and_group_relationships(AssetRelationshipGraph graph, Iterable[str] asset_ids, Optional[Dict[str, bool]] relationship_filters=None)
Collect and group relationships with directionality info in a single pass.
References _build_relationship_index.
Referenced by _create_relationship_traces.
Tuple[List[Optional[float]], List[Optional[float]], List[Optional[float]]] graph_visuals._build_edge_coordinates_optimized(List[dict] relationships, np.ndarray positions, Dict[str, int] asset_id_index)
Build edge coordinate lists for relationships using optimized O(1) lookups.
Referenced by _create_trace_for_group.
List[Optional[str]] graph_visuals._build_hover_texts(List[dict] relationships, str rel_type, bool is_bidirectional)
Build hover text list for relationships with pre-allocation for performance.
Referenced by _create_trace_for_group.
dict graph_visuals._get_line_style(str rel_type, bool is_bidirectional)
Get line style configuration for a relationship with color validation.
References _is_valid_color_format.
Referenced by _create_trace_for_group.
str graph_visuals._format_trace_name(str rel_type, bool is_bidirectional)
Format trace name for legend.
Referenced by _create_trace_for_group.
go.Scatter3d graph_visuals._create_trace_for_group(str rel_type, bool is_bidirectional, List[dict] relationships, np.ndarray positions, Dict[str, int] asset_id_index)
Create a single trace for a relationship group with optimized performance.
References _build_edge_coordinates_optimized, _build_hover_texts, _format_trace_name, _get_line_style.
Referenced by _create_relationship_traces.
List[go.Scatter3d] graph_visuals._create_relationship_traces(AssetRelationshipGraph graph, np.ndarray positions, List[str] asset_ids, Optional[Dict[str, bool]] relationship_filters=None)
Create separate traces for different types of relationships with enhanced visibility. Returns a list of traces for batch addition to figure using fig.add_traces() for optimal performance.
References _build_asset_id_index, _collect_and_group_relationships, _create_trace_for_group.
Referenced by _validate_visualization_data, visualize_3d_graph_with_filters.
List[go.Scatter3d] graph_visuals._create_directional_arrows(AssetRelationshipGraph graph, np.ndarray positions, List[str] asset_ids)
Create arrow markers for unidirectional relationships using vectorized NumPy operations. Returns a list of traces for batch addition to figure.
References _build_asset_id_index, _build_relationship_index.
Referenced by _add_directional_arrows_to_figure, _validate_visualization_data, visualize_3d_graph_with_filters.
None graph_visuals._validate_filter_parameters(Dict[str, bool] filter_params)
Validate that all filter parameters are boolean values. Args: filter_params: Dictionary mapping filter parameter names to their boolean values. Expected keys: show_same_sector, show_market_cap, show_correlation, show_corporate_bond, show_commodity_currency, show_income_comparison, show_regulatory, show_all_relationships, toggle_arrows Raises: TypeError: If any parameter is not a boolean or if filter_params is not a dictionary
Referenced by visualize_3d_graph_with_filters.
None graph_visuals._validate_relationship_filters(Optional[Dict[str, bool]] relationship_filters)
Validate relationship filter dictionary structure and values. Args: relationship_filters: Optional dictionary mapping relationship types to boolean visibility flags Raises: TypeError: If relationship_filters is not None and not a dictionary ValueError: If relationship_filters contains invalid keys or non-boolean values
Referenced by visualize_3d_graph_with_filters.
go.Figure graph_visuals.visualize_3d_graph_with_filters(AssetRelationshipGraph graph, bool show_same_sector=True, bool show_market_cap=True, bool show_correlation=True, bool show_corporate_bond=True, bool show_commodity_currency=True, bool show_income_comparison=True, bool show_regulatory=True, bool show_all_relationships=True, bool toggle_arrows=True)
Create 3D visualization with selective relationship filtering. This function dynamically creates and adds relationship traces based on optional filters, with comprehensive error handling to manage potential issues from invalid filter configurations or data inconsistencies. Args: graph: Asset relationship graph to visualize show_same_sector: Show same sector relationships (default: True) show_market_cap: Show market cap relationships (default: True) show_correlation: Show correlation relationships (default: True) show_corporate_bond: Show corporate bond relationships (default: True) show_commodity_currency: Show commodity currency relationships (default: True) show_income_comparison: Show income comparison relationships (default: True) show_regulatory: Show regulatory relationships (default: True) show_all_relationships: Master toggle to show all relationships (default: True) toggle_arrows: Show directional arrows for unidirectional relationships (default: True) Returns: Plotly Figure object with 3D visualization Raises: ValueError: If graph is invalid or missing required methods / attributes TypeError: If filter parameters are not boolean values
References _configure_3d_layout, _create_directional_arrows, _create_node_trace, _create_relationship_traces, _prepare_layout_config, _validate_filter_parameters, _validate_relationship_filters, _validate_visualization_data.