api::main
api::main.limiter
api::main.app
api::main.ENV
list api::main.allowed_origins
api::main.additional_origins
api::main.stripped_origin
api::main.allow_origins
api::main.allow_credentials
api::main.allow_methods
api::main.allow_headers
AssetRelationshipGraph api.main.get_graph()
Provide the global AssetRelationshipGraph, initialising it on first access if necessary. Returns: AssetRelationshipGraph: The global graph instance.
References api.main._initialize_graph.
Referenced by api.main.get_all_relationships, api.main.get_asset_detail, api.main.get_asset_relationships, api.main.get_assets, api.main.lifespan.
None api.main.set_graph(AssetRelationshipGraph graph_instance)
Set the module-level graph to the provided AssetRelationshipGraph and clear any configured graph factory. Parameters: graph_instance (AssetRelationshipGraph): Graph instance to use as the global graph.
None api.main.set_graph_factory(Optional[Callable[[], AssetRelationshipGraph]] factory)
Set the callable used to construct the global AssetRelationshipGraph on demand. If `factory` is a callable it will be used to build the graph the next time `get_graph()` is called. Passing `None` clears any configured factory. In all cases the current global graph instance is cleared so a new graph will be created on next access; this operation is performed in a thread-safe manner. Parameters: factory (Optional[Callable[[], AssetRelationshipGraph]]): A zero-argument callable that returns an `AssetRelationshipGraph`, or `None` to remove the factory and force recreation from defaults.
Referenced by api.main.reset_graph.
None api.main.reset_graph()
Clear the global graph and any configured factory so the graph will be reinitialised on next access. This removes any existing graph instance and clears the graph factory.
References api.main.set_graph_factory.
AssetRelationshipGraph api.main._initialize_graph()
Construct the asset relationship graph using the configured factory or environment-backed data sources. If a `graph_factory` is configured it is invoked. Otherwise, if `GRAPH_CACHE_PATH` is set a real-data graph is created (network access enabled when `USE_REAL_DATA_FETCHER` indicates real data should be used). If `GRAPH_CACHE_PATH` is not set but `USE_REAL_DATA_FETCHER` is true, `REAL_DATA_CACHE_PATH` is consulted to create a real-data graph. If neither real-data path nor real-data mode is available, a sample database graph is returned. Returns: AssetRelationshipGraph: The initialized graph instance.
References api.main._should_use_real_data_fetcher.
Referenced by api.main.get_graph.
bool api.main._should_use_real_data_fetcher()
Decides whether the application should use the real data fetcher based on the `USE_REAL_DATA_FETCHER` environment variable. Returns: `True` if `USE_REAL_DATA_FETCHER` is set to a truthy value (`1`, `true`, `yes`, `on`), `False` otherwise.
Referenced by api.main._initialize_graph.
api.main.lifespan(FastAPI _fastapi_app)
Manage the application's lifespan by initialising the global graph on startup and logging shutdown. Initialises the global asset relationship graph before the application begins handling requests; if initialisation fails the exception is re-raised to abort startup. Yields control for the application's running lifetime and logs on shutdown. Parameters: fastapi_app (FastAPI): The FastAPI application instance.
References api.main.get_graph.
api.main.login_for_access_token(Request request, OAuth2PasswordRequestForm form_data=Depends())
Create a JWT access token for a user authenticated with a username and password. Parameters: form_data (OAuth2PasswordRequestForm): Client-submitted credentials (`username` and `password`). Returns: dict: Mapping with `access_token` (JWT string) and `token_type` set to `'bearer'`.
api.main.read_users_me(Request request, User current_user=Depends(get_current_active_user))
Retrieve the currently authenticated user. Parameters: request (Request): Included for slowapi limiter dependency injection; unused by the function. current_user (User): Active user injected by the authentication dependency. Returns: The authenticated user.
bool api.main.validate_origin(str origin_url)
Determine whether an HTTP origin is permitted by the application's CORS rules. Allows explicitly configured origins, HTTPS origins with a valid domain, Vercel preview hostnames, HTTPS localhost/127.0.0.1 in any environment, and HTTP localhost/127.0.0.1 when ENV is "development". Parameters: origin_url (str): Origin URL to validate (for example "https://example.com" or "http://localhost:3000"). Returns: True if the origin is allowed, False otherwise.
None api.main.raise_asset_not_found(str asset_id, str resource_type="Asset")
Raise HTTPException for missing resources. Args: asset_id (str): ID of the asset that was not found. resource_type (str): Type of resource (default: "Asset").
Referenced by api.main.get_asset_detail, api.main.get_asset_relationships.
Dict[str, Any] api.main.serialize_asset(Any asset, bool include_issuer=False)
Serialize an Asset object to a dictionary representation. Args: asset: Asset object to serialize include_issuer: Whether to include issuer_id field (for detail views) Returns: Dictionary containing asset data with additional_fields
Referenced by api.main.get_asset_detail, api.main.get_assets.
api.main.root()
Provide basic API metadata and a listing of available endpoints. Returns: Dict[str, Union[str, Dict[str, str]]]: A mapping containing: - "message": short API description string. - "version": API version string. - "endpoints": dict mapping endpoint keys to their URL paths (e.g., "assets": "/api/assets").
api.main.health_check()
Health check endpoint
api.main.get_assets(Optional[str] asset_class=None, Optional[str] sector=None)
List assets, optionally filtered by asset class and sector. Parameters: asset_class (Optional[str]): Filter to include only assets whose `asset_class.value` equals this string. sector (Optional[str]): Filter to include only assets whose `sector` equals this string. Returns: List[AssetResponse]: AssetResponse objects matching the filters. Each object's `additional_fields` contains any non-null, asset-type-specific attributes as defined in the respective asset model classes.
References api.main.get_graph, api.main.serialize_asset.
api.main.get_asset_detail(str asset_id)
Retrieve detailed information for the asset identified by `asset_id`. Parameters: asset_id (str): Identifier of the asset whose details are requested. Returns: AssetResponse: Detailed asset information as defined in the AssetResponse model, including core fields and an `additional_fields` map containing any asset-specific attributes that are present and non-null. Raises: HTTPException: 404 if the asset is not found. HTTPException: 500 for unexpected errors while retrieving the asset.
References api.main.get_graph, api.main.raise_asset_not_found, api.main.serialize_asset.
api.main.get_asset_relationships(str asset_id)
List outgoing relationships for the specified asset. Parameters: asset_id (str): Identifier of the asset whose outgoing relationships are requested. Returns: List[RelationshipResponse]: Outgoing relationship records for the asset (each with source_id, target_id, relationship_type, and strength). Raises: HTTPException: 404 if the asset is not found; 500 for unexpected errors.
References api.main.get_graph, api.main.raise_asset_not_found.
api.main.get_all_relationships()
List all directed relationships in the initialized asset graph. Returns: List[RelationshipResponse]: List of relationships where each item contains `source_id`, `target_id`, `relationship_type`, and `strength`.
References api.main.get_graph.