tests::integration::test_debricked_workflow
tests::integration::test_debricked_workflow.REPO_ROOT
str tests::integration::test_debricked_workflow.DEBRICKED_WORKFLOW_FILE
str tests.integration.test_debricked_workflow.workflow_content()
Load raw content of the debricked workflow file once for the module.
Dict[str, Any] tests.integration.test_debricked_workflow.workflow_config(str workflow_content)
Parse YAML content once for the module.
Dict[str, Any] tests.integration.test_debricked_workflow.scan_job(Dict[str, Any] workflow_config)
Get the vulnerabilities-scan job configuration.
List[Dict[str, Any]] tests.integration.test_debricked_workflow.job_steps(Dict[str, Any] scan_job)
Get the list of steps from the scan job.
List[Dict[str, Any]] tests.integration.test_debricked_workflow.get_steps_by_action(List[Dict[str, Any]] steps, str action_substring)
Filter steps by action name (case-insensitive).
Referenced by tests.integration.test_debricked_workflow.TestStepsConfiguration.test_checkout_step_exists, tests.integration.test_debricked_workflow.TestStepsConfiguration.test_checkout_step_version_pinned, tests.integration.test_debricked_workflow.TestStepsConfiguration.test_debricked_action_exists, tests.integration.test_debricked_workflow.TestStepsConfiguration.test_debricked_action_version_pinned, tests.integration.test_debricked_workflow.TestSecretHandling.test_debricked_token_configuration, tests.integration.test_debricked_workflow.TestComplianceWithIssue492.test_uses_github_secrets.