graph_2d_visuals
graph_2d_visuals.logger
dict graph_2d_visuals.REL_TYPE_COLORS
Dict[str, Tuple[float, float]] graph_2d_visuals._create_circular_layout(List[str] asset_ids)
Create circular layout for 2D visualization. Args: asset_ids: List of asset IDs to position Returns: Dictionary mapping asset IDs to (x, y) positions on a unit circle
Referenced by visualize_2d_graph.
Dict[str, Tuple[float, float]] graph_2d_visuals._create_grid_layout(List[str] asset_ids)
Create grid layout for 2D visualization. Args: asset_ids: List of asset IDs to position Returns: Dictionary mapping asset IDs to (x, y) positions in a grid
Referenced by visualize_2d_graph.
Dict[str, Tuple[float, float]] graph_2d_visuals._create_spring_layout_2d(Dict[str, Tuple[float, float, float]] positions_3d, List[str] asset_ids)
Convert 3D spring layout positions to 2D by dropping z-coordinate. Args: positions_3d: Dictionary mapping asset IDs to (x, y, z) positions asset_ids: List of asset IDs Returns: Dictionary mapping asset IDs to (x, y) positions
Referenced by visualize_2d_graph.
List[go.Scatter] graph_2d_visuals._create_2d_relationship_traces(AssetRelationshipGraph graph, Dict[str, Tuple[float, float]] positions, List[str] asset_ids, bool show_same_sector=True, bool show_market_cap=True, bool show_correlation=True, bool show_corporate_bond=True, bool show_commodity_currency=True, bool show_income_comparison=True, bool show_regulatory=True, bool show_all_relationships=False)
Create 2D relationship traces with filtering. Args: graph: Asset relationship graph positions: Dictionary mapping asset IDs to (x, y) positions asset_ids: List of asset IDs show_same_sector: Show same sector relationships show_market_cap: Show market cap relationships show_correlation: Show correlation relationships show_corporate_bond: Show corporate bond relationships show_commodity_currency: Show commodity currency relationships show_income_comparison: Show income comparison relationships show_regulatory: Show regulatory relationships show_all_relationships: Master toggle to show all relationships Returns: List of Plotly Scatter traces for relationships
Referenced by visualize_2d_graph.
go.Figure graph_2d_visuals.visualize_2d_graph(AssetRelationshipGraph graph, str layout_type="spring", bool show_same_sector=True, bool show_market_cap=True, bool show_correlation=True, bool show_corporate_bond=True, bool show_commodity_currency=True, bool show_income_comparison=True, bool show_regulatory=True, bool show_all_relationships=False)
Create 2D visualization of asset relationship graph. Args: graph: Asset relationship graph to visualize layout_type: Layout algorithm to use ('spring', 'circular', 'grid') show_same_sector: Show same sector relationships show_market_cap: Show market cap relationships show_correlation: Show correlation relationships show_corporate_bond: Show corporate bond relationships show_commodity_currency: Show commodity currency relationships show_income_comparison: Show income comparison relationships show_regulatory: Show regulatory relationships show_all_relationships: Master toggle to show all relationships Returns: Plotly Figure object with 2D visualization
References _create_2d_relationship_traces, _create_circular_layout, _create_grid_layout, _create_spring_layout_2d.