real_data_fetcher
real_data_fetcher.logger
AssetRelationshipGraph real_data_fetcher.create_real_database()
Builds an AssetRelationshipGraph populated with market data, falling back to sample data when necessary. Creates or loads a graph containing assets, regulatory events and their relationships by attempting to: - load a cached graph if available, - fetch real market data when network access is enabled, - otherwise fall back to a provided or built sample dataset. Returns: AssetRelationshipGraph: The constructed graph populated with assets, regulatory events and relationship mappings; the content may come from the cache, a real-data fetch, or the sample fallback.
Any real_data_fetcher._enum_to_value(Any value)
Convert an Enum instance to its underlying value. Return the input unchanged otherwise. Parameters: value (Any): The value to normalise. If `value` is an `Enum` member its `.value` is returned. Returns: Any: The underlying value of the `Enum` member if applicable, otherwise the original `value`.
Referenced by _serialize_dataclass.
Dict[str, Any] real_data_fetcher._serialize_dataclass(Any obj)
Serialize a dataclass instance into a JSON-friendly dictionary with enum values converted. Parameters: obj (Any): A dataclass instance (e.g. Asset or subclass) to serialize. Returns: Dict[str, Any]: A mapping of field names to values where Enum members are replaced by their `.value`, and an additional "__type__" key containing the dataclass's class name.
References _enum_to_value.
Referenced by _serialize_graph.
Dict[str, Any] real_data_fetcher._serialize_graph(AssetRelationshipGraph graph)
Serialize an AssetRelationshipGraph into a JSON-serialisable dictionary. Parameters: graph (AssetRelationshipGraph): Graph to serialize. Returns: Dict[str, Any]: Dictionary containing: - "assets": list of serialized asset objects - "regulatory_events": list of serialized regulatory event objects - "relationships": mapping from source id to a list of outgoing relationships - "incoming_relationships": mapping from target id to a list of incoming relationships
References _serialize_dataclass.
Referenced by _save_to_cache.
Asset real_data_fetcher._deserialize_asset(Dict[str, Any] data)
Deserialize a dictionary representation of an asset back into an Asset instance. Parameters: data (Dict[str, Any]): Dictionary containing asset data with a "__type__" key indicating the asset subclass. Returns: Asset: An Asset instance (or subclass like Equity, Bond, etc.) constructed from the provided data.
Referenced by _deserialize_graph.
RegulatoryEvent real_data_fetcher._deserialize_event(Dict[str, Any] data)
Reconstructs a RegulatoryEvent from its serialized dictionary representation. The input dictionary is copied and its "event_type" field is converted to the RegulatoryActivity enum before creating the RegulatoryEvent instance. Parameters: data (Dict[str, Any]): Serialized event payload — must include an "event_type" value compatible with RegulatoryActivity and the remaining fields accepted by RegulatoryEvent. Returns: RegulatoryEvent: The deserialized RegulatoryEvent instance.
Referenced by _deserialize_graph.
AssetRelationshipGraph real_data_fetcher._deserialize_graph(Dict[str, Any] payload)
Reconstructs an AssetRelationshipGraph from a serialized payload. Parameters: payload (Dict[str, Any]): Serialized graph payload containing the keys "assets", "regulatory_events", "relationships", etc. Returns: AssetRelationshipGraph: Graph reconstructed from the payload.
References _deserialize_asset, _deserialize_event.
Referenced by _load_from_cache.
AssetRelationshipGraph real_data_fetcher._load_from_cache(Path path)
Load an AssetRelationshipGraph from a JSON cache file. Parameters: path (Path): Filesystem path to the cache JSON file to read. Returns: AssetRelationshipGraph: The graph reconstructed from the JSON payload.
References _deserialize_graph.
Referenced by real_data_fetcher.RealDataFetcher.create_real_database.
None real_data_fetcher._save_to_cache(AssetRelationshipGraph graph, Path path)
Persist an AssetRelationshipGraph to a JSON file at the given filesystem path. The function serialises the provided graph to JSON (UTF-8, pretty-printed with two-space indentation), creates parent directories if necessary, and overwrites any existing file at the path. Parameters: graph (AssetRelationshipGraph): The graph to persist. path (Path): Filesystem path where the JSON representation will be written.
References _serialize_graph.
Referenced by real_data_fetcher.RealDataFetcher.create_real_database.