api::database
str api::database.DATABASE_URL
str api::database.DATABASE_PATH
sqlite3 api::database._MEMORY_CONNECTION
api::database._MEMORY_CONNECTION_LOCK
str api.database._get_database_url()
Read the DATABASE_URL environment variable and return its value. Returns: The value of the `DATABASE_URL` environment variable. Raises: ValueError: If the `DATABASE_URL` environment variable is not set.
str api.database._resolve_sqlite_path(str url)
Resolve a SQLite URL to either a filesystem path or the special in-memory indicator. Accepts SQLite URLs with schemes like `sqlite:///relative.db`, `sqlite:////absolute/path.db`, and `sqlite:///:memory:`. Percent-encodings in the URL path are decoded before resolution. For in-memory URLs (`:memory:` or `/:memory:`) the literal string `":memory:"` is returned. URI-style memory databases like `sqlite:///file::memory:?cache=shared` are returned as-is. Parameters: url (str): SQLite URL to resolve. Returns: str: Filesystem path for file-based URLs, or the literal string `":memory:"` for in-memory databases, or the original path for URI-style memory databases.
bool api.database._is_memory_db(str|None path=None)
Determine whether the given or configured database refers to an in-memory SQLite database. Parameters: path (str | None): Optional database path or URI to evaluate. If omitted, the configured DATABASE_PATH is used. Returns: True if the path (or configured database) is an in-memory SQLite database. For example, ":memory:" or "file::memory:?cache=shared", False otherwise.
Referenced by api.database._connect, api.database.get_connection.
sqlite3.Connection api.database._connect()
Open a configured SQLite connection for the module's database path. Returns a persistent shared connection when the configured database is in-memory; for file-backed databases, returns a new connection instance. The connection has type detection enabled (PARSE_DECLTYPES), allows use from multiple threads (check_same_thread=False) and uses sqlite3.Row for rows. When the database path is a URI beginning with "file:" the connection is opened with URI handling enabled. Returns: sqlite3.Connection: A sqlite3 connection to the configured DATABASE_PATH (shared for in-memory, new per call for file-backed).
References api.database._is_memory_db.
Referenced by api.database.get_connection.
Iterator[sqlite3.Connection] api.database.get_connection()
Provide a context-managed SQLite connection for the configured database. For file-backed databases the connection is closed when the context exits; for in-memory databases the shared connection is kept open. Returns: sqlite3.Connection: The SQLite connection — closed on context exit for file-backed databases, kept open for in-memory databases.
References api.database._connect, api.database._is_memory_db.
Referenced by api.database.execute, api.database.fetch_one.
api.database._cleanup_memory_connection()
Clean up the global memory connection when the program exits.
None api.database.execute(str query, tuple|list|None parameters=None)
Execute a SQL write statement and commit the transaction using the module's managed SQLite connection. Parameters: query (str): SQL statement to execute. parameters (tuple | list | None): Sequence of values to bind to the statement; use `None` or an empty sequence if there are no parameters.
References api.database.get_connection.
Referenced by api.database.initialize_schema.
api.database.fetch_one(str query, tuple|list|None parameters=None)
Retrieve the first row produced by an SQL query. Parameters: query (str): SQL statement to execute. parameters (tuple | list | None): Optional sequence of parameters to bind into the query. Returns: sqlite3.Row | None: The first row of the result set as a `sqlite3.Row`, or `None` if the query returned no rows.
References api.database.get_connection.
Referenced by api.database.fetch_value.
api.database.fetch_value(str query, tuple|list|None parameters=None)
Fetches the first column value from the first row of a query result. Parameters: query (str): SQL query to execute; may include parameter placeholders. parameters (tuple | list | None): Sequence of parameters for the query placeholders. Returns: The first column value if a row is returned, `None` otherwise.
References api.database.fetch_one.
None api.database.initialize_schema()
Create the `user_credentials` table if it does not already exist. The table has the following columns: - `id`: INTEGER PRIMARY KEY AUTOINCREMENT - `username`: TEXT, unique and not null - `email`: TEXT - `full_name`: TEXT - `hashed_password`: TEXT, not null - `disabled`: INTEGER, not null, defaults to 0
References api.database.execute.