tests::integration::test_github_workflows
str tests::integration::test_github_workflows.BOOL_TAG
str tests::integration::test_github_workflows.WORKFLOWS_DIR
List[Path] tests.integration.test_github_workflows.get_workflow_files()
List workflow YAML files in the repository's .github/workflows directory. Returns: List[Path]: Paths to files with `.yml` or `.yaml` extensions found in the workflows directory; an empty list if the directory does not exist or no matching files are present.
Referenced by tests.integration.test_github_workflows.TestTestSuiteCompleteness.test_all_workflow_files_tested, tests.integration.test_github_workflows.TestWorkflowEdgeCases.test_at_least_one_workflow_exists.
Dict[str, Any] tests.integration.test_github_workflows.load_yaml_safe(Path file_path)
Parse a YAML file and return its content. Parameters: file_path (Path): Path to the YAML file to load. Returns: The parsed YAML content — a mapping, sequence, scalar value, or `None` if the document is empty. Raises: yaml.YAMLError: If the file contains invalid YAML.
Referenced by tests.integration.test_github_workflows.TestAutoAssignWorkflow.auto_assign_workflow, tests.integration.test_github_workflows.TestAutoAssignWorkflowAdvanced.auto_assign_workflow, tests.integration.test_github_workflows.TestPrAgentWorkflow.pr_agent_workflow, tests.integration.test_github_workflows.TestPrAgentWorkflowAdvanced.pr_agent_workflow, tests.integration.test_github_workflows.TestWorkflowAdvancedValidation.test_action_versions_use_semantic_versioning, tests.integration.test_github_workflows.TestWorkflowOutputsAndArtifactsAdvanced.test_artifacts_have_reasonable_retention, tests.integration.test_github_workflows.TestWorkflowCachingStrategies.test_cache_keys_are_unique_per_os, tests.integration.test_github_workflows.TestWorkflowAdvancedValidation.test_checkout_with_proper_ref_for_pr, tests.integration.test_github_workflows.TestWorkflowEnvironmentVariables.test_env_vars_not_duplicated_across_levels, tests.integration.test_github_workflows.TestWorkflowEnvironmentVariables.test_env_vars_use_consistent_naming, tests.integration.test_github_workflows.TestWorkflowConditionalExecution.test_if_conditions_use_valid_syntax, tests.integration.test_github_workflows.TestWorkflowAdvancedValidation.test_job_dependencies_are_acyclic, tests.integration.test_github_workflows.TestWorkflowOutputsAndArtifactsAdvanced.test_job_outputs_reference_valid_steps, tests.integration.test_github_workflows.TestWorkflowComplexScenarios.test_matrix_strategy_has_include_or_exclude_properly_formatted, tests.integration.test_github_workflows.TestWorkflowAdvancedSecurity.test_no_script_injection_in_run_commands, tests.integration.test_github_workflows.TestWorkflowPermissionsBestPractices.test_permissions_follow_least_privilege, tests.integration.test_github_workflows.TestWorkflowComplexScenarios.test_reusable_workflows_have_proper_inputs, tests.integration.test_github_workflows.TestWorkflowScheduledExecutionBestPractices.test_scheduled_workflows_not_too_frequent, tests.integration.test_github_workflows.TestWorkflowScheduledExecutionBestPractices.test_scheduled_workflows_use_valid_cron, tests.integration.test_github_workflows.TestWorkflowAdvancedValidation.test_timeout_minutes_are_reasonable, tests.integration.test_github_workflows.TestWorkflowActions.test_workflow_actions_have_versions, tests.integration.test_github_workflows.TestWorkflowOutputsAndArtifacts.test_workflow_artifacts_have_retention, tests.integration.test_github_workflows.TestWorkflowComplexity.test_workflow_deep_nesting_in_conditionals, tests.integration.test_github_workflows.TestWorkflowEnvAndSecrets.test_workflow_env_vars_naming_convention, tests.integration.test_github_workflows.TestWorkflowStructure.test_workflow_has_jobs, tests.integration.test_github_workflows.TestWorkflowStructure.test_workflow_has_name, tests.integration.test_github_workflows.TestWorkflowStructure.test_workflow_has_triggers, tests.integration.test_github_workflows.TestWorkflowComplexity.test_workflow_job_count_reasonable, tests.integration.test_github_workflows.TestWorkflowStructure.test_workflow_jobs_have_steps, tests.integration.test_github_workflows.TestWorkflowJobConfiguration.test_workflow_jobs_specify_runner, tests.integration.test_github_workflows.TestWorkflowJobConfiguration.test_workflow_jobs_use_standard_runners, tests.integration.test_github_workflows.TestWorkflowOutputsAndArtifacts.test_workflow_outputs_referenced_correctly, tests.integration.test_github_workflows.TestWorkflowTriggers.test_workflow_pr_triggers_specify_types, tests.integration.test_github_workflows.TestWorkflowBestPractices.test_workflow_shell_explicitly_set, tests.integration.test_github_workflows.TestWorkflowComplexity.test_workflow_step_count_per_job, tests.integration.test_github_workflows.TestWorkflowStepConfiguration.test_workflow_steps_continue_on_error_usage, tests.integration.test_github_workflows.TestWorkflowMaintainability.test_workflow_steps_have_descriptive_names, tests.integration.test_github_workflows.TestWorkflowActions.test_workflow_steps_have_names_or_uses, tests.integration.test_github_workflows.TestWorkflowStepConfiguration.test_workflow_steps_with_id_are_unique, tests.integration.test_github_workflows.TestWorkflowStepConfiguration.test_workflow_steps_with_working_directory, tests.integration.test_github_workflows.TestWorkflowBestPractices.test_workflow_timeout_specified, tests.integration.test_github_workflows.TestWorkflowTriggers.test_workflow_triggers_are_valid_types, tests.integration.test_github_workflows.TestWorkflowPerformance.test_workflow_uses_caching, tests.integration.test_github_workflows.TestWorkflowBestPractices.test_workflow_uses_concurrency_for_prs, tests.integration.test_github_workflows.TestWorkflowSecurity.test_workflow_uses_secrets_context, tests.integration.test_github_workflows.TestWorkflowPermissionsBestPractices.test_write_permissions_have_justification.
List[str] tests.integration.test_github_workflows.check_duplicate_keys(Path file_path)
Detect duplicate mapping keys in a YAML file. Parameters: file_path (Path): Path to the YAML file to inspect. Returns: List of duplicate key names found, or an empty list if none are present.
Referenced by tests.integration.test_github_workflows.TestWorkflowSyntax.test_workflow_no_duplicate_keys.