conftest
bool conftest._cov_plugin_available()
Check whether the pytest-cov plugin is importable. Returns: `True` if the pytest-cov plugin is importable, `False` otherwise.
Referenced by pytest_load_initial_conftests, tests.unit.test_root_conftest.TestCovPluginAvailable.test_cov_plugin_available_uses_importlib, tests.unit.test_root_conftest.TestCovPluginAvailable.test_cov_plugin_available_when_installed, tests.unit.test_root_conftest.TestCovPluginAvailable.test_cov_plugin_not_available_when_not_installed.
None conftest.pytest_load_initial_conftests(List[str] args, early_config, parser)
Remove pytest-cov related command-line options from the provided argument list when the pytest-cov plugin is not available. If the plugin is present the argument list is left unchanged. Otherwise, remove occurrences of --cov and --cov-report together with their following parameters. Also remove any inline forms starting with --cov= or --cov-report=. The original `args` list is updated in-place. Parameters: args (List[str]): Mutable list of command-line arguments; coverage-related options are removed from this list in-place.
References _cov_plugin_available.
Referenced by tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_does_nothing_when_cov_plugin_available, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_handles_args_with_only_coverage_flags, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_consecutive_coverage_flags, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_cov_flag_at_end_with_no_value, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_cov_flags_with_complex_values, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_cov_in_test_path, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_cov_report_at_end_with_no_value, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_handles_empty_args_list, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_handles_mixed_equals_and_space_syntax, tests.unit.test_root_conftest.TestRealWorldScenarios.test_local_development_without_cov, tests.unit.test_root_conftest.TestRealWorldScenarios.test_mixed_short_and_long_flags, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_modifies_args_in_place, tests.unit.test_root_conftest.TestRealWorldScenarios.test_multiple_coverage_sources, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_preserves_other_flags, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_preserves_similar_but_different_flags, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_removes_cov_flag_with_equals_syntax, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_removes_cov_flag_with_value, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_removes_cov_report_flag_with_equals_syntax, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_removes_cov_report_flag_with_value, tests.unit.test_root_conftest.TestPytestLoadInitialConftests.test_removes_multiple_coverage_flags, tests.unit.test_root_conftest.TestCoverageFilteringEdgeCases.test_skip_next_flag_resets_correctly, tests.unit.test_root_conftest.TestRealWorldScenarios.test_typical_ci_environment_args.