name: Issue and PR auto-assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    branches: [main]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    if: github.event_name == 'issues' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign new issues and PRs
        uses: pozil/auto-assign-issue@af6beea6bdf1e8eb373f061c5bc168681fc6d011 # v4.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "mohavro"
          numOfAssignee: 1
