name: Issue and PR auto-assign

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign new issues and PRs
        uses: pozil/auto-assign-issue@65947009a243e6b3993edeef4e64df3ca85d760c # v1.14.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "mohavro"
          numOfAssignee: 1
