name: Debricked scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  vulnerabilities_scan:
    name: Vulnerability Scan
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Debricked Scan
        uses: debricked/actions/scan@3a23c0b4689c231887ffe1f29ac8b0b20e38de62
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
