name: Greetings

permissions:
  issues: write
  pull-requests: write

"on":
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Thanks for opening your first issue! A maintainer will review it soon.
        pr-message: |
          🎉 Thanks for your first pull request! Our CI checks will run automatically.
