name: Pylint

permissions:
  contents: read

"on":
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - '.github/workflows/pylint.yml'
      - '!**/*.md'
      - '!docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - '.github/workflows/pylint.yml'
      - '!**/*.md'
      - '!docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Python CI common for pylint (${{ matrix.python-version }})
      uses: ./.github/actions/ci-common
      with:
        language: python
        python-version: ${{ matrix.python-version }}
        dependency-paths: |
          requirements.txt
          requirements-dev.txt
        install: |
          python -m pip install --upgrade pip && \
          pip install pylint && pip install -r requirements-dev.txt
        test: |
          pylint $(git ls-files '*.py')
