on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: "28 10 * * *"
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - run: |
        if [ -z "$SEMGREP_APP_TOKEN" ]; then
          unset SEMGREP_APP_TOKEN
          SEMGREP_RULES=p/default semgrep ci
        else
          semgrep ci
        fi
